services:
  telerin:
    build: ./TeleRin_backend
    container_name: telerin
    ports:
      - "1240:1240"
    volumes:
      - ./TeleRin_backend:/TELERIN
    environment:
      PYTHONUNBUFFERED: 1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: TeleRin
    depends_on:
      - db
    restart: always
    stdin_open: true
    tty: true

  frontend:
    build: ./TeleRin_frontend/TeleRinEND
    container_name: telerin_frontend
    ports:
      - "4210:4210"
    volumes:
      - ./TeleRin_frontend/TeleRinEND:/TELERINFRONTEND
      - /TELERINFRONTEND/node_modules
    environment:
      - VITE_API_URL=http://telerin:1240
    depends_on:
      - telerin
    restart: always
    stdin_open: true
    tty: true

  db:
    image: postgres:18
    container_name: database
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: TeleRin
    volumes:
      - ./TeleRin_backend/db-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
